#!/bin/bash
These are some inconsistent notes about cross-compiling lierolibre, they
should eventually be added as repository content or makefile targets.

# boost program_options compile-able subset
bcp build program_options boost-program_options/

# build boost subset
cd boost-program_options/
./bootstrap.sh
echo -e "\n\nusing gcc : mingw32 : i686-w64-mingw32-g++ ;" >> tools/build/v2/user-config.jam
./b2 toolset=gcc-mingw32 target-os=windows link=shared --layout=tagged -sNO_BZIP2=1 -sNO_ZLIB=1

# zlib
make -f win32/Makefile.gcc PREFIX=i686-w64-mingw32-

# for SDL, libconfig, ...
./configure --host=i686-w64-mingw32
make

# for lierolibre itself
./configure --host=i686-w64-mingw32
make CPPFLAGS="-Ilib -Ilib/libconfig/lib" LDFLAGS="-Llib/SDL_mixer/lib/x86 -lSDL_mixer -Llib/libconfig-1.4.8/lib/.libs -llibconfig++ -Llib/SDL-1.2.15/build/.libs -lSDL -Llib/zlib-1.2.6 -lz -Llib/boost-program_options/stage/lib -llibboost_program_options-mt -static-libgcc -static-libstdc++"
cp .libs/lierolibre.exe lierolibre.exe
i686-w64-mingw32-strip lierolibre.exe

